# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MCnegloglikCpp <- function(beta, z, y, tau) {
    .Call(`_MCMVR_MCnegloglikCpp`, beta, z, y, tau)
}

MCgradbetaCpp <- function(beta, x, y, xtx, xty, tau) {
    .Call(`_MCMVR_MCgradbetaCpp`, beta, x, y, xtx, xty, tau)
}

